### ISSUE TITLE
Problème avec les lignes de présence prévue + congés

### ISSUE THREAD

**Issue by mistraloz** [studio1247/gertrude#22]
Lorsqu'un enfant a un congé prévu, line.reference est non défini et, donc, l'affichage du planning se fait mal (page noire). Attention, cela ne le fait pas en antériorité. Uniquement sur le planning future. Il doit y avoir une raison à ça mais cela m'échappe. 

Voici la stack trace de l'erreur :

AttributeError: 'LigneConge' object has no attribute 'reference'
Traceback (most recent call last):
  File "/home/mistral/www/Optimomes/gertrude/software/panel_planning.py", line 329, in onNextWeek
    self.OnChangementSemaine()
  File "/home/mistral/www/Optimomes/gertrude/software/panel_planning.py", line 302, in OnChangementSemaine
    self.UpdateWeek()
  File "/home/mistral/www/Optimomes/gertrude/software/panel_planning.py", line 320, in UpdateWeek
    note.SetData(site, groupe, day)
  File "/home/mistral/www/Optimomes/gertrude/software/panel_planning.py", line 186, in SetData
    self.UpdateContents()
  File "/home/mistral/www/Optimomes/gertrude/software/panel_planning.py", line 159, in UpdateContents
    self.SetLines(self.lignes_enfants + self.lignes_salaries)
  File "/home/mistral/www/Optimomes/gertrude/software/planning.py", line 912, in SetLines
    self.internal_panel.SetLines(lines)
  File "/home/mistral/www/Optimomes/gertrude/software/planning.py", line 730, in SetLines
    self.UpdateLine(i)
  File "/home/mistral/www/Optimomes/gertrude/software/planning.py", line 571, in UpdateLine
    text = line.GetDynamicText(line)
  File "/home/mistral/www/Optimomes/gertrude/software/panel_planning.py", line 102, in GetHeuresEnfant
    heures_reference = line.reference.GetNombreHeures()

**Comment by bsongis** [comment]
Le problème est présent dans la version officielle ? Je ne reproduis pas le problème. Si c'est le cas voudriez-vous m'envoyer une BDD par MP en me précisant quel enfant / quel jour regarder ? Merci !
